modLoader="javafml" #mandatory
#
loaderVersion="[25,)" #mandatory (24 is current forge version)
#
issueTrackerURL="https://github.com/Shadows-of-Fire/Attained-Drops-2/issues" #optional
#
displayURL="https://minecraft.curseforge.com/projects/attained-drops-2" #optional
#
authors="Shadows_of_Fire" #optional
#
[[mods]] #mandatory
#
modId="attained_drops" #mandatory
#
version="${version}" #mandatory
#
displayName="Attained Drops" #mandatory
#
description='''
A mod for farming mob drops.
'''
#
[[dependencies.attained_drops]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.attained_drops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"